[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "youtube_search"
version = "0.1.0"
authors = []
description = "A lightweight YouTube search utility"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "requests>=2.0.0",
]